apiVersion: apps/v1
kind: Deployment
metadata:
  name: netflix-clone
  namespace: staging
  annotations:
    kubernetes.io/change-cause: "Force redeployment to update image"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: netflix-clone
  template:
    metadata:
      labels:
        app: netflix-clone
    spec:
      imagePullSecrets:
      - name: my-registry-secret  # Reference your secret here
      containers:
      - name: netflix-clone
        image: sivanext/netflix_clone:latest
        imagePullPolicy: Always  # Correct indentation here
        ports:
        - containerPort: 5000
